create table if not exists users (
  id bigint generated by default as identity primary key,
  username varchar(50) not null unique,
  email varchar(100) not null unique,
  hashed_password varchar(255) not null,
  role varchar(20) not null,
  fcm_token varchar(255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists labours (
  id varchar(50) primary key,
  full_name varchar(100) not null,
  phone varchar(20) not null,
  skill_type varchar(20) not null,
  daily_wage numeric(10,2) not null,
  joining_date date not null,
  aadhaar_number varchar(20) not null unique,
  address text not null,
  emergency_contact varchar(20) not null,
  is_active boolean not null default true,
  is_freezed boolean not null default false,
  avatar_url varchar(255),
  license_number varchar(80),
  license_expiry_date date,
  salary_per_month numeric(10,2),
  advance_entries jsonb,
  pdf_attachment_name varchar(255),
  gender varchar(10),
  profile_photo text,
  profile_photo_name varchar(255),
  aadhaar_pdf_name varchar(255),
  aadhaar_pdf_data text,
  license_pdf_name varchar(255),
  license_pdf_data text,
  custom_documents jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  labour_id varchar(50) not null references labours(id) on delete cascade,
  date date not null,
  status varchar(20) not null,
  reason varchar(255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_attendance_labour_date unique (labour_id, date)
);

create table if not exists salary_payments (
  id varchar(50) primary key,
  labour_id varchar(50) not null references labours(id) on delete cascade,
  date date not null,
  amount_calculated numeric(10,2) not null,
  advance_deducted numeric(10,2) not null default 0,
  bonus numeric(10,2) not null default 0,
  net_paid numeric(10,2) not null,
  status varchar(20) not null,
  salary_option varchar(20) not null,
  deduct_amount_requested numeric(10,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists vehicles (
  id varchar(50) primary key,
  vehicle_name varchar(100),
  vehicle_type varchar(30) not null,
  brand varchar(50) not null,
  model varchar(50) not null,
  registration_date date,
  insurance_expiry date not null,
  fitness_expiry date,
  pollution_expiry date not null,
  driver_name varchar(100),
  rc_expiry date,
  insurance_number varchar(100),
  next_service_due date,
  rc_book_pdf varchar(255),
  insurance_pdf varchar(255),
  permit_pdf varchar(255),
  fitness_pdf varchar(255),
  rc_book_data text,
  insurance_data text,
  permit_data text,
  fitness_data text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists business_bills (
  id varchar(50) primary key,
  invoice_no varchar(50) not null unique,
  client_name varchar(150) not null,
  bill_date date not null,
  due_date date not null,
  description text not null,
  amount numeric(12,2) not null,
  tax_rate numeric(10,2) not null default 0,
  status varchar(20) not null default 'Pending',
  borewell_type varchar(30),
  bill_mode varchar(20),
  existing_depth int,
  final_depth int,
  casing_feet int,
  casing_rate numeric(10,2),
  batta numeric(10,2),
  starting_price numeric(10,2),
  old_feet_rate numeric(10,2),
  casing_type varchar(20),
  calculated_breakdown jsonb,
  total_drilling_charges numeric(12,2),
  casing_charges numeric(12,2),
  is_custom_bill boolean,
  location varchar(150),
  broker_name varchar(150),
  custom_date_type varchar(20),
  custom_starting_feet int,
  custom_ending_feet int,
  casing10_feet int,
  casing10_rate numeric(10,2),
  casing7_feet int,
  casing7_rate numeric(10,2),
  custom_slab_rates jsonb,
  discount_amount numeric(10,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists fuel_entries (
  id varchar(50) primary key,
  vehicle_id varchar(50) references vehicles(id) on delete set null,
  date date,
  liters numeric(10,2),
  cost numeric(10,2),
  current_odometer int,
  fuel_type varchar(20),
  per_liter_cost numeric(10,2),
  date_time timestamptz,
  vehicle_name varchar(100),
  total_amount numeric(10,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists trips (
  id varchar(50) primary key,
  vehicle_id varchar(50) references vehicles(id) on delete set null,
  date date not null,
  start_location varchar(100) not null,
  end_location varchar(100) not null,
  distance_covered numeric(10,2) not null,
  revenue_earned numeric(10,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists loans_given (
  id varchar(50) primary key,
  borrower_name varchar(100),
  person_name varchar(100),
  mobile_number varchar(20),
  address text,
  loan_amount numeric(12,2),
  amount_given numeric(12,2),
  interest_rate numeric(5,2),
  interest_percentage numeric(5,2),
  start_date date,
  end_date date,
  emi_amount numeric(10,2),
  due_date varchar(20),
  total_paid numeric(12,2),
  is_defaulter boolean,
  interest_type varchar(20),
  category varchar(50),
  status varchar(20),
  monthly_interests jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists loans_received (
  id varchar(50) primary key,
  lender_name varchar(100),
  person_name varchar(100),
  my_name varchar(100),
  borrowed_amount numeric(12,2),
  amount numeric(12,2),
  interest_rate numeric(5,2),
  interest_percentage numeric(5,2),
  start_date date,
  end_date date,
  monthly_emi numeric(10,2),
  due_date varchar(20),
  total_repaid numeric(12,2),
  interest_type varchar(20),
  interest_status varchar(20),
  category varchar(50),
  status varchar(20),
  vehicle_id varchar(50),
  number_of_months int,
  monthly_interests jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists family_members (
  id varchar(50) primary key,
  name varchar(100) not null,
  relationship_name varchar(50) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists income_entries (
  id varchar(50) primary key,
  source varchar(100) not null,
  amount numeric(12,2) not null,
  date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists family_expenses (
  id varchar(50) primary key,
  family_member_name varchar(100),
  member_id varchar(50) references family_members(id) on delete set null,
  date date not null,
  reason varchar(50),
  category varchar(50),
  amount numeric(12,2) not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists category_budgets (
  category varchar(50) primary key,
  "limit" numeric(12,2) not null,
  spent numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists documents (
  id varchar(50) primary key,
  name varchar(150) not null,
  type varchar(50) not null,
  owner_name varchar(100) not null,
  upload_date date not null,
  file_size varchar(20) not null,
  expiry_date date,
  status varchar(20) not null default 'Active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists notifications (
  id varchar(50) primary key,
  title varchar(150) not null,
  body text not null,
  date varchar(50) not null,
  type varchar(50) not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
